on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '3 21 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        bin/scrape
    - name: Commit and push if it changed
      run: |-
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
